### ISSUE TITLE
cdms2=3.1.4=*_3 has pins of libnetcdf that are too loose

### ISSUE THREAD

**Issue by xylar** [conda-forge/cdms2-feedstock#55]
I'm having trouble with environments picking up build 3 of the latest `cdms2` instead of build 10, presumably at least partly because the pins on build 3 are too loose:
```
libnetcdf >=4.6.2,<5.0a0
```
Here's a typical error:
```
Traceback (most recent call last):
  File "/opt/conda/envs/e3sm-unified-nox/bin/e3sm_diags", line 7, in <module>
    from acme_diags.acme_diags_driver import main
  File "/opt/conda/envs/e3sm-unified-nox/lib/python3.7/site-packages/acme_diags/acme_diags_driver.py", line 23, in <module>
    import cdms2.tvariable 
  File "/opt/conda/envs/e3sm-unified-nox/lib/python3.7/site-packages/cdms2/__init__.py", line 8, in <module>
    from . import dataset
  File "/opt/conda/envs/e3sm-unified-nox/lib/python3.7/site-packages/cdms2/dataset.py", line 8, in <module>
    from . import Cdunif
ImportError: libnetcdf.so.13: cannot open shared object file: No such file or directory
```

It would be nice to patch that build to make the `libnetcdf` pins stricter:
```
libnetcdf >=4.6.2,<4.6.3a0
```

This seems to be possible:
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe
but i"m not clear on the details.

**Comment by xylar** [comment]
Now that we are at cdms2=3.1.5, I think this can be closed.  I worked around this by explicitly forcing build 10 to install when I needed to avoid build 3.
